// pages/_app.tsx
import { Amplify } from "aws-amplify";
import config from "@/amplifyconfiguration.json";
import "@aws-amplify/ui-react/styles.css";
import type { AppProps } from "next/app";
import { LegacyConfig } from "aws-amplify/adapter-core";

// configure the Amplify client library with the configuration generated by `amplify sandbox`
Amplify.configure(
  {
    ...config,
    aws_user_files_s3_bucket: process.env.IS_DEVELOPMENT
      ? "amplify-amplizon-xss-sandbox-edf1a8-bucket83908e77-ew8bziwdsenv"
      : "amplify-d2lgoq62e7b8fm-main-branch--bucket83908e77-zvho4kifp9xe",
    aws_user_files_s3_bucket_region: "us-west-2",
  } as unknown as LegacyConfig,
  { ssr: true },
);

function App({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />;
}

export default App;
